services:
  db:
    image: postgres:17
    container_name: rails_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: rails_api
    depends_on:
      db:
        condition: service_healthy  
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      VITE_API_USERNAME: ${VITE_API_USERNAME}
      VITE_API_PASSWORD: ${VITE_API_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - ./api:/rails
    command: >
      sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0"

  redis:
    image: redis:alpine
    container_name: rails_redis
    restart: always
    ports:
      - "6379:6379"

  sidekiq:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: rails_sidekiq
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      VITE_API_USERNAME: ${VITE_API_USERNAME}
      VITE_API_PASSWORD: ${VITE_API_PASSWORD}
      REDIS_URL: redis://redis:6379/0
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]

  test:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: rails_test
    environment:
      RAILS_ENV: test
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      VITE_API_USERNAME: ${VITE_API_USERNAME}
      VITE_API_PASSWORD: ${VITE_API_PASSWORD}
    volumes:
      - ./api:/rails
    depends_on:
      - db
    command: >
      sh -c "bundle exec rails db:create db:migrate && bundle exec rspec"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    stdin_open: true
    tty: true
    
volumes:
  postgres_data:
